language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -e .
  - pip install .[testing]
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install python-coveralls
# command to run tests
before_script:
  - cd src
script: 
  - pytest tests/test.py --cov=src
after_success:
  - coveralls
